title: blender2pmxem document
description: >-
  blender2pmxem の使い方

collections:
  features:
    output: true
  misc:
    output: true

exclude: [README.md, Gemfile, Gemfile.lock]

url: https://blender2pmxem.netlify.com/

lang: ja_JP

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
